'path':
    '/ec/res4/scratch/snh02/DE_observations/mtg_li_l2_processed_5km/%Y/%m/%d/'
'format':
    'filename':
        'flash': 'flash_accumulation_%Y%m%d_%H.nc'
    'fileformat': 'netCDF'
'vars':
    'flash':
        'var': 'flash_accumulation'
        'postprocess': False
        'res': '5 km'
        'description': '1-hour Flash density'
        'units': 'km**-2'
        'verif':
            'times':
                'accum_hours': 12
                'freq_verif': 48
            'FSS': 
                'thresholds': [0.5, 1, 5, 10, 25]
                'scales': [1, 4, 6, 8, 10]
            'SAL':
                'f': 0.50
                'q': 0.95
                'tstorm_kwargs': {"max_num_features": None, "minref": 35, "maxref": 48, "mindiff": 6, "minsize": 50, "minmax": 41, "mindis": 10}
