'path':
    '/ec/res4/hpcperm/snh02/DE_observations/mtg_li_l2_processed_5km/%Y/%m/%d/'
'format':
    'filename':
        'flashdens': 'flash_accumulation_%Y%m%d_%H.nc'
    'fileformat': 'netCDF'
'vars':
    'flashdens':
        'var': 'flash_accumulation'
        'postprocess': True
        'res': '5 km'
        'description': 'Flash density'
        'units': 'strikes per km2'
        'verif':
            'times':
                'accum_hours': 0
                'freq_verif': 1
            'FSS': 
                'thresholds': [10, 20, 30, 40, 50]
                'scales': [4, 6, 8, 10, 12, 14]
            'SAL':
                'f': 0.50
                'q': 0.95
                'tstorm_kwargs': {"max_num_features": None, "minref": 35, "maxref": 48, "mindiff": 6, "minsize": 50, "minmax": 41, "mindis": 10}
