Filenames:
  regrid: "SIMULATIONS/@exp@/data_regrid/@init_time@/@exp@_@var_verif@_@obs_db@grid_@case@_acc@accum@h_@init_time@+%LL.nc"
  plot_orig: "PLOTS/side_plots/plots_@obs@/@case@/@exp@/@exp_model_filename@_@exp@_orig_acc@accum@h_@init_time@+%LL.png"
  plot_regrid: "PLOTS/side_plots/plots_@obs@/@case@/@exp@/@exp_model_filename@_@exp@_regrid_vs_@obs@_acc@accum@h_@init_time@+%LL.png"
  pickle_fss: "pickles/FSS/@obs@/@case@/@exp@/FSS_@exp_model_filename@_@exp@_@obs@_acc@accum@h_@init_time@.pkl"
  plot_fss: "PLOTS/side_plots/plots_verif/FSS/@obs@/@case@/@exp@/FSS_@exp_model_filename@_@exp@_@obs@_acc@accum@h_@init_time@+%LL.png"
  pickle_sal: "pickles/SAL/@obs@/@case@/@exp@/SAL_@exp_model_filename@_@exp@_@obs@_acc@accum@h_@init_time@.pkl"
  plot_objects: "PLOTS/side_plots/plots_verif/SAL/@obs@/@case@/@exp@/DetectedObjects_@obs@_@exp@_acc@accum@h_@init_time@+%LL.png"
  plot_sal: "PLOTS/side_plots/plots_verif/SAL/@obs@/@case@/@exp@/SAL_@exp_model_filename@_@exp@_@obs@_acc@accum@h_@init_time@+%LL.png"
  plot_fss_init: "PLOTS/side_plots/plots_verif/FSS/@obs@/@case@/@exp@/FSS_@exp_model_filename@_@exp@_@obs@_acc@accum@h_@init_time@_mean.png"
  plot_sal_init: "PLOTS/side_plots/plots_verif/SAL/@obs@/@case@/@exp@/SAL_@exp_model_filename@_@exp@_@obs@_acc@accum@h_@init_time@_all.png"
  plot_fss_dist: "PLOTS/side_plots/plots_verif/FSS/@obs@/@case@/@exp@/FSSdist_@exp_model_filename@_@exp@_@obs@_@init_time@.png"
  plot_sal_dist: "PLOTS/side_plots/plots_verif/SAL/@obs@/@case@/@exp@/SALdist_@exp_model_filename@_@exp@_@obs@_@init_time@.png"
  plot_panel: "PLOTS/side_plots/plots_verif/panels/@obs@/@case@/@exp@/panel_@exp_model_filename@_@exp@_@obs@_acc@accum@h_@init_time@+%LL.png"
  plot_frame: "PLOTS/side_plots/plots_verif/gif_frames/@obs@/@case@/@exp@_@obs@_@init_time@+%LL.png"
  plot_gif: "PLOTS/main_plots/@case@/@case@_@exp@_@obs@.gif"
Plots:
  title_orig: "@exp_model@ [exp: @exp@] (orig grid)\nRun: @init_time@ UTC\nValid on %Y-%m-%d at %Hz (+%LL)"
  title_regrid: "@exp_model@ [exp: @exp@] (regrid)\nRun: @init_time@ UTC\nValid on %Y-%m-%d at %Hz (+%LL)"
  title_obs: "@obs_db@\nValid on %Y-%m-%d at %Hz"
  title_fss: "FSS plot | OBS: @obs@\n@exp_model@ [@exp@]\nValid: @init_time@+%LL"
  title_sal: "SAL plot | OBS: @obs@\n@exp_model@ [@exp@]\nValid: @init_time@+%LL"
  title_fss_period: "FSS plot | @obs@\n@exp_model@ [@exp@]\nValid: from @init_time@+%LL1 to @init_time@+%LL2"
  title_sal_period: "SAL plot | @obs@\n@exp_model@ [@exp@]\nValid: from @init_time@+%LL1 to @init_time@+%LL2"
  title_fss_dist: "FSS distribution - @exp_model@ | @exp@ | @obs@ | @init_time@"
  title_sal_dist: "SAL distribution - @exp_model@ | @exp@ | @obs@ | @init_time@"
