'path':
    '/path/to/downloaded/observations'
'format':
    'filename':
        '': ''
    'fileformat': ''
'vars':
    '':
        'var': ''
        'postprocess': 
        'res': ''
	    'description': ''
	    'units': ''
        'verif':
            'times':
                'accum_hours': 1
                'freq_verif': 1
            'FSS': 
                'thresholds': []
                'scales': []
            'SAL':
                'f': 
                'q': 
                'tstorm_kwargs': {"max_num_features": , "minref": , "maxref": , "mindiff": , "minsize": , "minmax": , "mindis": }

