'model':
    'name': ''
'format':
    'filepaths':
        - 
    'filename': ''
    'fileformat': ''
'inits':
    '':
        'path': 
        'fcast_horiz': ''
'vars':
    '':
        'var': 
        'accum': 
        'postprocess': ''
        'find_min':
        'verif_0h':  
    'lat':
        'var': ''
        'description': ''
    'lon':
        'var': ''
        'description': ''
